ALTER USER sys IDENTIFIED BY password;

ALTER SESSION SET CONTAINER = orclpdb1;

CREATE USER testapp17_2738 IDENTIFIED BY password;

GRANT CREATE SESSION TO testapp17_2738;

GRANT CREATE TABLE TO testapp17_2738;

ALTER USER testapp17_2738 QUOTA UNLIMITED ON USERS;

